import { ApiSchema } from "@nestjs/swagger";
import { Exclude, plainToInstance } from "class-transformer";

import { ChatMessage } from "generated/prisma/client";

@ApiSchema({ description: "A stored question and answer about a transcript" })
export class ChatMessageEntity implements ChatMessage {
	static fromPlain(plain: Partial<ChatMessageEntity>): ChatMessageEntity {
		return plainToInstance(ChatMessageEntity, plain);
	}

	/**
	 * The unique identifier for the chat message.
	 * @example "123e4567-e89b-12d3-a456-426614174000"
	 */
	id: string;

	/**
	 * The unique identifier of the transcript this message belongs to.
	 * @example "123e4567-e89b-12d3-a456-426614174000"
	 */
	@Exclude()
	transcriptId: string;

	/**
	 * The question that was asked.
	 * @example "What is the main topic discussed?"
	 */
	question: string;

	/**
	 * The answer generated by the model.
	 * @example "The main topic discussed is..."
	 */
	answer: string;

	/**
	 * The date and time when this message was created.
	 * @example "2024-01-01T00:00:00.000Z"
	 */
	createdAt: Date;
}
