services:
    server:
        image: ghcr.io/clearhearbg/clearhear-server:latest
        restart: always
        env_file:
            - .env
        environment:
            - POSTGRES_HOST=postgres:5432
        ports:
            - "8393:8393"
        extra_hosts:
            - "localhost:host-gateway"
        depends_on:
            - postgres

    postgres:
        image: postgres:18-alpine
        restart: always
        env_file:
            - .env
        ports:
            - "${POSTGRES_PORT:-5432}:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
